### ISSUE TITLE
way to input commercial datasets

### ISSUE THREAD

**Issue by mkunst23** [hubmapconsortium/spatial-transcriptomics-pipeline#36]
Hi,

I wanted to try to use the pipeline after the decoding step to run segmentation using data from a MERSCOPE. Is there a place I can see how to format the data to match the output of the previous steps?

Thanks,
Michael

**Comment by nickeener** [comment]
Hey @mkunst23 thanks for the interest in our tool! Though for what you want to do I don't think PIPEFISH will be the best option. The main reason being that in order to run segmentation using PIPEFISH, you'd need to convert your segmentation images to SpaceTx format which will be very wasteful memory wise. Segmentation images are considered "auxillary" images in our pipeline while the mRNA probe images are considered "primary" images. You can have a dataset with only primary images and no auxillary images but not the other way around so you'd need to include those mRNA probe images for the conversion (not sure if MERSCOPE retains these or deletes them after processing), even though they wouldn't be used at all (putting in "dummy" primary images with just a single hybridization round here MIGHT work but no guarantees). You would also need to format that decoded transcript information into an xarray object with a specific set of fields and then save it as a netcdf file.
 
PIPEFISH has two main segmentation options (excluding importing premade segmentation labels): an in-house watershed-based pipeline, and CellPose (an external tool that we've imported into PIPEFISH). The watershed-based pipeline isn't particularly novel, just watershed-segmentation of the binary thresholded image followed by some steps to clean up the results (see the functions ```segment_nuclei```, ```segment_cytoplasm```, and ```segmentByDensity``` in the [segmentationDriver](https://github.com/hubmapconsortium/spatial-transcriptomics-pipeline/blob/master/bin/segmentationDriver.py) file). The version of Cellpose in our pipeline is exactly the same as the [main repo version](https://github.com/MouseLand/cellpose), except it is less flexible because there are only a few parameters that you can specify the value for when running it through PIPEFISH.

For these reasons I think you should look into performing segmentation yourself instead of having PIPEFISH do it. I'd recommend using CellPose with a custom trained model as that has been how I've obtained high quality 3D segmentations for these kind of datasets.

**Comment by mkunst23** [comment]
Hi @nickeener, 

Thanks for the quick reply. I see your point. I was primarily interested in the tool because you already implemented a solution for merging segmentations of the same cell in different z-planes. Ultimately we are planning to have our own pipeline for post-processing just wanted to see If you already have a good solution for our problem.

**Comment by nickeener** [comment]
@mkunst23 stitching of segmentations across z slices is actually something that is implemented natively in CellPose (use the ```stitch_threshold``` parameter) so again I'd suggest that for your purposes. Good luck with your research!
